package zmaster587.advancedRocketry.api;

import net.minecraft.tileentity.TileEntityType;
import zmaster587.advancedRocketry.tile.TileAtmosphereDetector;
import zmaster587.advancedRocketry.tile.TileDrill;
import zmaster587.advancedRocketry.tile.TileFluidTank;
import zmaster587.advancedRocketry.tile.TileForceFieldProjector;
import zmaster587.advancedRocketry.tile.TileMachineChipInfo;
import zmaster587.advancedRocketry.tile.TilePump;
import zmaster587.advancedRocketry.tile.TileRocketBuilder;
import zmaster587.advancedRocketry.tile.TileSeal;
import zmaster587.advancedRocketry.tile.TileSolarPanel;
import zmaster587.advancedRocketry.tile.TileStationBuilder;
import zmaster587.advancedRocketry.tile.TileSuitWorkStation;
import zmaster587.advancedRocketry.tile.Satellite.TileChipStorage;
import zmaster587.advancedRocketry.tile.Satellite.TileEntitySatelliteControlCenter;
import zmaster587.advancedRocketry.tile.Satellite.TileSatelliteBuilder;
import zmaster587.advancedRocketry.tile.cables.TilePipe;
import zmaster587.advancedRocketry.tile.cables.TileWirelessTransciever;
import zmaster587.advancedRocketry.tile.data.TileDataProgrammer;
import zmaster587.advancedRocketry.tile.hatch.TileDataBus;
import zmaster587.advancedRocketry.tile.infrastructure.TileEntityFuelingStation;
import zmaster587.advancedRocketry.tile.infrastructure.TileEntityMoniteringStation;
import zmaster587.advancedRocketry.tile.infrastructure.TileGuidanceComputerHatch;
import zmaster587.advancedRocketry.tile.infrastructure.TileRocketLoader;
import zmaster587.advancedRocketry.tile.infrastructure.TileRocketUnloader;
import zmaster587.advancedRocketry.tile.multiblock.TileAstrobodyDataProcessor;
import zmaster587.advancedRocketry.tile.multiblock.TileAtmosphereTerraformer;
import zmaster587.advancedRocketry.tile.multiblock.TileBeacon;
import zmaster587.advancedRocketry.tile.multiblock.TileBiomeScanner;
import zmaster587.advancedRocketry.tile.multiblock.TileGravityController;
import zmaster587.advancedRocketry.tile.multiblock.TileObservatory;
import zmaster587.advancedRocketry.tile.multiblock.TilePlanetSelector;
import zmaster587.advancedRocketry.tile.multiblock.TileRailgun;
import zmaster587.advancedRocketry.tile.multiblock.TileSpaceElevator;
import zmaster587.advancedRocketry.tile.multiblock.TileSpaceLaser;
import zmaster587.advancedRocketry.tile.multiblock.TileWarpCore;
import zmaster587.advancedRocketry.tile.multiblock.energy.TileBlackHoleGenerator;
import zmaster587.advancedRocketry.tile.multiblock.energy.TileMicrowaveReciever;
import zmaster587.advancedRocketry.tile.multiblock.machine.TileCentrifuge;
import zmaster587.advancedRocketry.tile.multiblock.machine.TileChemicalReactor;
import zmaster587.advancedRocketry.tile.multiblock.machine.TileCrystallizer;
import zmaster587.advancedRocketry.tile.multiblock.machine.TileCuttingMachine;
import zmaster587.advancedRocketry.tile.multiblock.machine.TileElectricArcFurnace;
import zmaster587.advancedRocketry.tile.multiblock.machine.TileElectrolyser;
import zmaster587.advancedRocketry.tile.multiblock.machine.TileLathe;
import zmaster587.advancedRocketry.tile.multiblock.machine.TilePrecisionAssembler;
import zmaster587.advancedRocketry.tile.multiblock.machine.TileRollingMachine;
import zmaster587.advancedRocketry.tile.oxygen.TileCO2Scrubber;
import zmaster587.advancedRocketry.tile.oxygen.TileOxygenCharger;
import zmaster587.advancedRocketry.tile.oxygen.TileOxygenVent;
import zmaster587.advancedRocketry.tile.station.TileDockingPort;
import zmaster587.advancedRocketry.tile.station.TileLandingPad;
import zmaster587.advancedRocketry.tile.station.TilePlanetaryHologram;
import zmaster587.advancedRocketry.tile.station.TileStationAltitudeController;
import zmaster587.advancedRocketry.tile.station.TileStationGravityController;
import zmaster587.advancedRocketry.tile.station.TileStationOrientationControl;
import zmaster587.advancedRocketry.tile.station.TileWarpShipMonitor;
import zmaster587.libVulpes.tile.multiblock.hatch.TileFluidHatch;

public class AdvancedRocketryTileEntityType {
	public static TileEntityType<TilePipe> TILE_POWER_PIPE;
	public static TileEntityType<TilePipe> TILE_FLUID_PIPE;
	public static TileEntityType<TilePipe> TILE_DATA_PIPE;
	public static TileEntityType<TileWirelessTransciever> TILE_WIRELESS_TRANSCIEVER;
	public static TileEntityType<TileDataProgrammer> TILE_DATA_PROGRAMMER;
	public static TileEntityType<TileDataBus> TILE_DATA_BUS;
	public static TileEntityType<TileEntityFuelingStation> TILE_FUELING_STATION;
	public static TileEntityType<TileEntityMoniteringStation> TILE_MONITORIING_STATION;
	public static TileEntityType<TileGuidanceComputerHatch> TILE_GUIDANCE_COMPUTER_HATCH;
	public static TileEntityType<TileFluidHatch> TILE_FLUID_LOADER;
	public static TileEntityType<TileFluidHatch> TILE_FLUID_UNLOADER;
	public static TileEntityType<TileRocketLoader> TILE_ROCKET_LOADER;
	public static TileEntityType<TileRocketUnloader> TILE_ROCKET_UNLOADER;
	public static TileEntityType<TileBlackHoleGenerator> TILE_BLACK_HOLE_GENERATOR;
	public static TileEntityType<TileMicrowaveReciever> TILE_MICROWAVE_RECIEVER;
	public static TileEntityType<TileCentrifuge> TILE_CENTRIFUGE;
	public static TileEntityType<TileChemicalReactor> TILE_CHEMICAL_REACTOR;
	public static TileEntityType<TileCrystallizer> TILE_CRYSTALLIZER;
	public static TileEntityType<TileCuttingMachine> TILE_CUTTING_MACHINE;
	public static TileEntityType<TileElectricArcFurnace> TILE_ARC_FURNACE;
	public static TileEntityType<TileElectrolyser> TILE_ELECTROLYSER;
	public static TileEntityType<TileLathe> TILE_LATHE;
	public static TileEntityType<TilePrecisionAssembler> TILE_PREC_ASS;
	public static TileEntityType<TileRollingMachine> TILE_ROLLING;
	public static TileEntityType<TileAstrobodyDataProcessor> TILE_ASTROBODY_DATA;
	public static TileEntityType<TileAtmosphereTerraformer> TILE_TERRAFORMER;
	public static TileEntityType<TileBeacon> TILE_BEACON;
	public static TileEntityType<TileBiomeScanner> TILE_BIOME_SCANNER;
	public static TileEntityType<TileGravityController> TILE_GRAVITY_CONTROLLER;
	public static TileEntityType<TileObservatory> TILE_OBSERVATORY;
	public static TileEntityType<TilePlanetSelector> TILE_PLANET_SELECTOR;
	public static TileEntityType<TileRailgun> TILE_RAILGUN;
	public static TileEntityType<TileSpaceElevator> TILE_SPACE_ELEVATOR;
	public static TileEntityType<TileSpaceLaser> TILE_SPACE_LASER;
	public static TileEntityType<TileWarpCore> TILE_WARP_CORE;
	public static TileEntityType<TileCO2Scrubber> TILE_CO2_SCRUBBER;
	public static TileEntityType<TileOxygenCharger> TILE_OXYGEN_CHARGER;
	public static TileEntityType<TileOxygenVent> TILE_OXYGEN_VENT;
	public static TileEntityType<TileChipStorage> TILE_CHIP_STORAGE;
	public static TileEntityType<TileEntitySatelliteControlCenter> TILE_SAT_CONTROL;
	public static TileEntityType<TileSatelliteBuilder> TILE_SAT_BUILDER;
	public static TileEntityType<TileDockingPort> TILE_DOCKING_PORT;
	public static TileEntityType<TileLandingPad> TILE_LANDING_PAD;
	public static TileEntityType<TilePlanetaryHologram> TILE_HOLOGRAM;
	public static TileEntityType<TileStationAltitudeController> TILE_ALT_CONTROLLER;
	public static TileEntityType<TileStationOrientationControl> TILE_ORIENTATION_CONTROLLER;
	public static TileEntityType<TileWarpShipMonitor> TILE_WARP_SHIP_CONTROLLER;
	public static TileEntityType<TileAtmosphereDetector> TILE_ATM_DETECTOR;
	public static TileEntityType<TileDrill> TILE_DRILL;
	public static TileEntityType<TileFluidTank> TILE_FLUID_TANK;
	public static TileEntityType<TileForceFieldProjector> TILE_FORCE_FIELD_PROJECTOR;
	public static TileEntityType<TileMachineChipInfo> TILE_CHIP_MACHINE;
	public static TileEntityType<TilePump> TILE_PUMP;
	public static TileEntityType<TileRocketBuilder> TILE_ROCKET_BUILDER;
	public static TileEntityType<TileSolarPanel> TILE_SOLAR_PANEL;
	public static TileEntityType<TileStationBuilder> TILE_STATION_BUILDER;
	public static TileEntityType<TileSuitWorkStation> TILE_WORK_STATION;
	public static TileEntityType<TileSeal> TILE_SEAL;
}
